name: CI/CD on macOS

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test (Gradle)
        run: |
          chmod +x gradlew  # Ensure Gradle Wrapper is executable
          ./gradlew clean build

  docker-deploy:
    runs-on: self-hosted
    needs: build-test
    steps:
      - name: Build Docker Image with Jib
        run: ./gradlew jibDockerBuild

      - name: Run with Docker Compose
        run: docker-compose up -d
